# Generated by Django 5.0.6 on 2024-09-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Description',
            new_name='description',
        ),
    ]
