# Generated by Django 5.0.6 on 2025-02-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
